=== Lizaveta-CR/10_JavaST_2020/part2task03/src/main/resources/data/orders.xsd
<?xml version="1.0" encoding="UTF-8"?>


<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://tsvirko.by/order"
        xmlns:tns="http://tsvirko.by/order"
        attributeFormDefault="unqualified" elementFormDefault="qualified">

    <element name="orders">
        <complexType>
            <sequence>
                <element name="order" type="tns:Order" minOccurs="0" maxOccurs="unbounded"></element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Order">
        <sequence>
            <element name="person" type="tns:Person"></element>
            <element name="products" type="tns:Products" minOccurs="1" maxOccurs="5"></element>
            <!--            <element name="price" type="decimal"></element>-->
        </sequence>
        <attribute name="order_id" type="tns:Id" use="required"/>
        <attribute name="order_date" type="date" use="optional" default="2020-09-27"></attribute>
    </complexType>

    <complexType name="Person">
        <sequence>
            <element name="email" type="string"></element>
            <element name="telephone" type="tns:Telephone"></element>
            <element name="address" type="tns:Address"></element>
        </sequence>
        <attribute name="login" type="tns:login" use="required"/>
    </complexType>

    <complexType name="Address">
        <all>
            <element name="country" type="tns:country"/>
            <element name="city" type="string"/>
            <element name="street" type="string"/>
            <element name="house_number" type="int"/>
            <element name="apartment_number" type="int"/>
        </all>
    </complexType>

    <complexType name="ProductItem">
        <sequence>
            <element name="type" type="tns:type"/>
            <element name="price" type="decimal"/>
            <element name="producer" type="tns:Producer"/>
        </sequence>
    </complexType>

    <complexType name="Products">
        <sequence>
            <element name="amount" type="int"/>
            <element name="product" type="tns:ProductItem"/>
        </sequence>
    </complexType>

    <complexType name="Producer">
        <sequence>
            <element name="producer_name" type="string"/>
            <element name="producer_country" type="tns:country"/>
        </sequence>
    </complexType>

    <!--    <simpleType name="email">-->
    <!--        <restriction base="string">-->
    <!--            <pattern-->
    <!--                    value="^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$"/>-->
    <!--        </restriction>-->
    <!--    </simpleType>-->

    <simpleType name="country">
        <restriction base="string">
            <pattern value="[A-Z]{2,3}"/>
        </restriction>
    </simpleType>

    <simpleType name="type">
        <restriction base="string">
            <enumeration value="guitar"/>
            <enumeration value="cello"/>
            <enumeration value="violin"/>
            <enumeration value="drum"/>
            <enumeration value="saxophone"/>
            <enumeration value="accordion"/>
            <enumeration value="piano"/>
            <enumeration value="flute"/>
        </restriction>
    </simpleType>

    <simpleType name="Id">
        <restriction base="ID">
            <pattern value="[A-z]{1,5}[0-9]{1,5}"/>
        </restriction>
    </simpleType>

    <simpleType name="login">
        <restriction base="ID">
            <pattern value="(\w){8,20}"/>
        </restriction>
    </simpleType>
    <simpleType name="Telephone">
        <restriction base="long">
            <pattern value="(\d){13}"/>
        </restriction>
    </simpleType>
</schema>

=== Lizaveta-CR/10_JavaST_2020/part2task04_WEB/src/main/resources/data/orders.xml
<?xml version="1.0" encoding="UTF-8"?>

<orders xmlns="http://tsvirko.by/order"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://tsvirko.by/order orders.xsd">
    <order order_id="O1" order_date="2020-11-26">
        <person login="LizaTs2000">
            <email>eliza@gmail.com</email>
            <telephone>3754411111111</telephone>
            <address>
                <country>BY</country>
                <city>Minsk</city>
                <street>Lenina</street>
                <apartment_number>11</apartment_number>
                <house_number>12</house_number>
            </address>
        </person>
        <products>
            <amount>2</amount>
            <product>
                <type>guitar</type>
                <price>123.67</price>
                <producer>
                    <producer_name>Takamine</producer_name>
                    <producer_country>JP</producer_country>
                </producer>
            </product>
        </products>
        <products>
            <amount>1</amount>
            <product>
                <type>violin</type>
                <price>567.99</price>
                <producer>
                    <producer_name>Takamine</producer_name>
                    <producer_country>JP</producer_country>
                </producer>
            </product>
        </products>
    </order>
    <order order_id="O2">
        <person login="Misha2345">
            <email>miha@gmail.com</email>
            <telephone>3753311211721</telephone>
            <address>
                <country>CN</country>
                <city>Beijing</city>
                <street>中国第一街</street>
                <apartment_number>2</apartment_number>
                <house_number>12</house_number>
            </address>
        </person>
        <products>
            <amount>1</amount>
            <product>
                <type>saxophone</type>
                <price>388.99</price>
                <producer>
                    <producer_name>Peace</producer_name>
                    <producer_country>TW</producer_country>
                </producer>
            </product>
        </products>
    </order>
    <order order_id="O3" order_date="2020-09-09">
        <person login="Waivabrs">
            <email>toledymmiza-8247@yopmail.com</email>
            <telephone>3754411111111</telephone>
            <address>
                <country>RU</country>
                <city>Moscow</city>
                <street>Ostozenka</street>
                <apartment_number>1</apartment_number>
                <house_number>22</house_number>
            </address>
        </person>
        <products>
            <amount>1</amount>
            <product>
                <type>piano</type>
                <price>2098.20</price>
                <producer>
                    <producer_name>Yamaha</producer_name>
                    <producer_country>ID</producer_country>
                </producer>
            </product>
        </products>
        <products>
            <amount>1</amount>
            <product>
                <type>violin</type>
                <price>567.99</price>
                <producer>
                    <producer_name>Takamine</producer_name>
                    <producer_country>JP</producer_country>
                </producer>
            </product>
        </products>
    </order>
    <order order_id="O4" order_date="2019-02-12">
        <person login="Vagetost28">
            <email>dexeniny-9232@yopmail.com</email>
            <telephone>3751127121212</telephone>
            <address>
                <country>US</country>
                <city>New-York</city>
                <street>Park Avenue</street>
                <apartment_number>23</apartment_number>
                <house_number>12</house_number>
            </address>
        </person>
        <products>
            <amount>2</amount>
            <product>
                <type>drum</type>
                <price>2777.30</price>
                <producer>
                    <producer_name>Roland</producer_name>
                    <producer_country>TW</producer_country>
                </producer>
            </product>
        </products>
    </order>
    <order order_id="O5" order_date="2020-10-01">
        <person login="LizUhd007">
            <email>KjEliza@gmail.com</email>
            <telephone>3754481621233</telephone>
            <address>
                <country>CA</country>
                <city>Toronto</city>
                <street>Yonge Street</street>
                <apartment_number>33</apartment_number>
                <house_number>65</house_number>
            </address>
        </person>
        <products>
            <amount>1</amount>
            <product>
                <type>accordion</type>
                <price>162.99</price>
                <producer>
                    <producer_name>Weltmeister</producer_name>
                    <producer_country>DE</producer_country>
                </producer>
            </product>
        </products>
    </order>
    <order order_id="O6" order_date="2020-01-26">
        <person login="KsuSokol123">
            <email>KsuSokol123@gmail.com</email>
            <telephone>3753382611111</telephone>
            <address>
                <country>BY</country>
                <city>Grodno</city>
                <street>Lenina</street>
                <apartment_number>222</apartment_number>
                <house_number>12</house_number>
            </address>
        </person>
        <products>
            <amount>1</amount>
            <product>
                <type>flute</type>
                <price>1232.67</price>
                <producer>
                    <producer_name>Brahner</producer_name>
                    <producer_country>CN</producer_country>
                </producer>
            </product>
        </products>
        <products>
            <amount>1</amount>
            <product>
                <type>violin</type>
                <price>567.99</price>
                <producer>
                    <producer_name>Takamine</producer_name>
                    <producer_country>JP</producer_country>
                </producer>
            </product>
        </products>
    </order>
    <order order_id="O7" order_date="2020-02-07">
        <person login="NikAzar2000">
            <email>nikitaAzaroz@mail.ru</email>
            <telephone>3753372521111</telephone>
            <address>
                <country>BY</country>
                <city>Brest</city>
                <street>Gogolya</street>
                <apartment_number>111</apartment_number>
                <house_number>9</house_number>
            </address>
        </person>
        <products>
            <amount>1</amount>
            <product>
                <type>violin</type>
                <price>567.99</price>
                <producer>
                    <producer_name>Takamine</producer_name>
                    <producer_country>JP</producer_country>
                </producer>
            </product>
        </products>
    </order>
    <order order_id="O8" order_date="2020-05-19">
        <person login="SashaAv22">
            <email>sashkaAverin@gmail.com</email>
            <telephone>3752999211112</telephone>
            <address>
                <country>DE</country>
                <city>Munhen</city>
                <street>Tal</street>
                <apartment_number>18</apartment_number>
                <house_number>2</house_number>
            </address>
        </person>
        <products>
            <amount>1</amount>
            <product>
                <type>cello</type>
                <price>8762.82</price>
                <producer>
                    <producer_name>Cremona</producer_name>
                    <producer_country>CN</producer_country>
                </producer>
            </product>
        </products>
    </order>
    <order order_id="O9" order_date="2020-04-03">
        <person login="dasDasKr">
            <email>dashkaKrav@gmail.com</email>
            <telephone>3754417741111</telephone>
            <address>
                <country>BY</country>
                <city>Gomel</city>
                <street>Lenina</street>
                <apartment_number>223</apartment_number>
                <house_number>11</house_number>
            </address>
        </person>
        <products>
            <amount>1</amount>
            <product>
                <type>violin</type>
                <price>567.99</price>
                <producer>
                    <producer_name>Takamine</producer_name>
                    <producer_country>JP</producer_country>
                </producer>
            </product>
        </products>
    </order>
</orders>

=== Lizaveta-CR/10_JavaST_2020/part2task03/src/main/resources/data/orders.xml
<?xml version="1.0" encoding="UTF-8"?>

<orders xmlns="http://tsvirko.by/order"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://tsvirko.by/order orders.xsd">
    <order order_id="O1" order_date="2020-11-26">
        <person person_id="P1">
            <email>eliza@gmail.com</email>
            <telephone>3754411111111</telephone>
            <address address_id="A1">
                <country>BY</country>
                <city>Minsk</city>
                <street>Lenina</street>
            </address>
        </person>
        <products>
            <amount>2</amount>
            <product>
                <type>guitar</type>
                <price>123.67</price>
                <producer>
<!--                    <producer_id>PRD1</producer_id>-->
                    <producer_name>Takamine</producer_name>
                    <producer_country>JP</producer_country>
                </producer>
            </product>
        </products>
        <products>
            <amount>1</amount>
            <product>
                <type>violin</type>
                <price>567.99</price>
                <producer>
<!--                    <producer_id>PRD1</producer_id>-->
                    <producer_name>Takamine</producer_name>
                    <producer_country>JP</producer_country>
                </producer>
            </product>
        </products>
    </order>
</orders>
